import type { Metadata } from "next";
import { Figtree, Cute_Font } from "next/font/google";
import "./globals.css";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} bg-gradient-to-r from-slate-50 via-slate-50 to-slate-200`}>
        {children}
      </body>
    </html>
  );
}
